// SPDX-FileCopyrightText: 2025 2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
//
// SPDX-License-Identifier: Apache-2.0

import { describe, it, expect } from 'vitest';
import {
  WEAVE_STORE_AZURE_WEB_PUBSUB,
  WEAVE_STORE_AZURE_WEB_PUBSUB_CONNECTION_STATUS,
  WEAVE_STORE_HORIZONTAL_SYNC_HANDLER_CLIENT_TYPE,
  WEAVE_STORE_AZURE_WEB_PUBSUB_DESTROY_ROOM_STATUS,
  WEAVE_STORE_AZURE_WEB_PUBSUB_SYNC_CLIENT_DEFAULT_OPTIONS,
  WEAVE_STORE_AZURE_WEB_PUBSUB_SYNC_HOST_DEFAULT_OPTIONS,
} from '../constants';

describe('constants', () => {
  it('WEAVE_STORE_AZURE_WEB_PUBSUB has correct value', () => {
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB).toBe('store-azure-web-pubsub');
  });

  it('WEAVE_STORE_AZURE_WEB_PUBSUB_CONNECTION_STATUS has all expected values', () => {
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_CONNECTION_STATUS.CONNECTING).toBe('connecting');
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_CONNECTION_STATUS.CONNECTED).toBe('connected');
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_CONNECTION_STATUS.DISCONNECTED).toBe('disconnected');
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_CONNECTION_STATUS.ERROR).toBe('error');
  });

  it('WEAVE_STORE_HORIZONTAL_SYNC_HANDLER_CLIENT_TYPE has all expected values', () => {
    expect(WEAVE_STORE_HORIZONTAL_SYNC_HANDLER_CLIENT_TYPE.PUB).toBe('pub');
    expect(WEAVE_STORE_HORIZONTAL_SYNC_HANDLER_CLIENT_TYPE.SUB).toBe('sub');
  });

  it('WEAVE_STORE_AZURE_WEB_PUBSUB_DESTROY_ROOM_STATUS has all expected values', () => {
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_DESTROY_ROOM_STATUS.NOT_FOUND).toBe('not-found');
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_DESTROY_ROOM_STATUS.NOT_CONNECTED).toBe('not-connected');
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_DESTROY_ROOM_STATUS.DESTROYED).toBe('destroyed');
  });

  it('WEAVE_STORE_AZURE_WEB_PUBSUB_SYNC_CLIENT_DEFAULT_OPTIONS has correct structure', () => {
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_SYNC_CLIENT_DEFAULT_OPTIONS.clientConnection.timeoutMs).toBe(60000);
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_SYNC_CLIENT_DEFAULT_OPTIONS.heartbeat.checkWindowTimeMs).toBe(60000);
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_SYNC_CLIENT_DEFAULT_OPTIONS.heartbeat.checkIntervalMs).toBe(15000);
  });

  it('WEAVE_STORE_AZURE_WEB_PUBSUB_SYNC_HOST_DEFAULT_OPTIONS has correct structure', () => {
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_SYNC_HOST_DEFAULT_OPTIONS.heartbeat.sendIntervalMs).toBe(5000);
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_SYNC_HOST_DEFAULT_OPTIONS.resync.checkIntervalMs).toBe(60000);
    expect(WEAVE_STORE_AZURE_WEB_PUBSUB_SYNC_HOST_DEFAULT_OPTIONS.resync.attemptsLimit).toBe(12);
  });
});
