// SPDX-FileCopyrightText: 2025 2025 INDUSTRIA DE DISEÑO TEXTIL S.A. (INDITEX S.A.)
//
// SPDX-License-Identifier: Apache-2.0

import { defineConfig } from 'tsdown';

export default [
  defineConfig({
    entry: {
      server: './src/index.server.ts',
    },
    external: [
      '@inditextech/weave-sdk',
      'node:crypto',
      'node:events',
      'node:http',
      'node:https',
      'node:net',
      'node:os',
      'node:process',
      'node:stream',
      'node:tls',
      'node:url',
      'node:util',
      'node:zlib',
      'crypto',
      'events',
      'http',
      'https',
      'net',
      'os',
      'process',
      'stream',
      'tls',
      'url',
      'util',
      'zlib',
    ],
    format: ['es'],
    target: 'es2023',
    clean: true,
    dts: true,
    platform: 'node',
    report: true,
  }),
  defineConfig({
    entry: {
      client: './src/index.client.ts',
    },
    external: [
      '@inditextech/weave-sdk',
      'node:crypto',
      'node:events',
      'node:http',
      'node:https',
      'node:net',
      'node:os',
      'node:process',
      'node:stream',
      'node:tls',
      'node:url',
      'node:util',
      'node:zlib',
      'crypto',
      'events',
      'http',
      'https',
      'net',
      'os',
      'process',
      'stream',
      'tls',
      'url',
      'util',
      'zlib',
    ],
    format: ['es'],
    target: 'es2023',
    clean: true,
    dts: true,
    platform: 'browser',
  }),
];
