= WeavePenToolAction

The **WeavePenToolAction** action allows users to draw continuos lines on the canvas
with N segments, by clicking N times to define the N segments. This tool is ideal for
sketching, annotating, or creating custom shapes.

Each line is captured as a Line Node with configurable styling, and is instantly synchronized
across all connected users.

When active the user will iterate on the following steps:

* **Click** or **Touch** on the canvas, to define a segment start point.
* **Click** or **Touch** again on the canvas, to define a segment final point.

When the user is satisfied with the segments:

* On non-touch devices, press the keys kbd:[Enter] or kbd:[Esc].
* On touch devices, select again the xref:api-reference:sdk/actions/selection-tool.adoc[Selection Tool].

Then the line with the N defined segments is added to the canvas as a fully functional
node—ready. This action integrates seamlessly with **Weave.js's** real-time state system,
ensuring the new element appears instantly for all connected users.

== Import

[source,typescript]
----
import { WeavePenToolAction } from "@inditextech/weavejs-sdk";
----

== Instantiation

[source,typescript]
----
new WeavePenToolAction(config?: WeavePenToolCallbacks);
----

== Configuration

[source,typescript]
----
type WeavePenToolCallbacks = {
  onPropsChange?: WeaveActionPropsChangeCallback; // <1>
}
----
<1> `onPropsChange` (optional): A callback function that is called when the properties
of the action change. The callback receives an object as parameter with the

== Methods

=== updateProps

[source,typescript]
----
updateProps(props: WeaveElementAttributes): void;
----

Update the properties of the action. Ideal for setting properties of the line, like
its color, stroke size, etc.

== Events

If the keys kbd:[Enter] or kbd:[Esc] are pressed, the action is cancelled.

On touch devices, select again the xref:api-reference:sdk/actions/selection-tool.adoc[Selection Tool]
to finish or cancel the action.

== TypeScript Types

[source,typescript]
----
type WeaveActionPropsChangeCallback = (
  props: WeaveElementAttributes
) => void;

type WeaveElementAttributes = {
  [key: string]: any;
  id?: string;
  nodeType?: string;
  children?: WeaveStateElement[];
};

type WeaveStateElement = {
  key: string;
  type: string;
  props: WeaveElementAttributes;
};

type WeavePenToolCallbacks = {
  onPropsChange?: WeaveActionPropsChangeCallback;
}
----
