= WeaveRectangleToolAction

The **WeaveRectangleToolAction** action enables users to create new rectangle nodes.
When active the user can:

* **Click** on the canvas, it will create a rectangle with a default size.
* **Touch** on the canvas, it will create a rectangle with a default size.
* **Click & drag** to create a rectangle and define its size.

Once clicked or click-drag finishes, the rectangle is added to the canvas as a fully functional
node—ready. This action integrates seamlessly with **Weave.js's** real-time state system,
ensuring the new element appears instantly for all connected users.

== Import

[source,typescript]
----
import { WeaveRectangleToolAction } from "@inditextech/weavejs-sdk";
----

== Instantiation

[source,typescript]
----
new WeaveRectangleToolAction(config?: WeaveRectangleToolCallbacks);
----

== Configuration

[source,typescript]
----
type WeaveRectangleToolCallbacks = {
  onPropsChange?: WeaveActionPropsChangeCallback; // <1>
}
----
<1> `onPropsChange` (optional): A callback function that is called when the properties
of the action change. The callback receives an object as parameter with the

== Methods

=== updateProps

[source,typescript]
----
updateProps(props: WeaveElementAttributes): void;
----

Update the properties of the action. Ideal for setting properties of the rectangle, like
its color, stroke size, etc. 

== Events

If the keys kbd:[Enter] or kbd:[Esc] are pressed, the action is cancelled.

On touch devices, select again the xref:api-reference:sdk/actions/selection-tool.adoc[Selection Tool]
to finish or cancel the action.

== TypeScript Types

[source,typescript]
----
type WeaveActionPropsChangeCallback = (
  props: WeaveElementAttributes
) => void;

type WeaveElementAttributes = {
  [key: string]: any;
  id?: string;
  nodeType?: string;
  children?: WeaveStateElement[];
};

type WeaveStateElement = {
  key: string;
  type: string;
  props: WeaveElementAttributes;
};

type WeaveRectangleToolCallbacks = {
  onPropsChange?: WeaveActionPropsChangeCallback;
}
----
