= WeaveFrameToolAction

The **WeaveFrameToolAction** action allows users to create frame nodes by clicking
and position the frame on the canvas. A frame acts as a visual container for organizing
other nodes, often used to group related content, define sections, or build modular layouts.

When active the user:

* Clicks on an empty canvas space to add the frame.

Then the frame is added to the canvas as a fully functional node—ready.
This action integrates seamlessly with **Weave.js's** real-time state system,
ensuring the new element appears instantly for all connected users.

== Import

[source,typescript]
----
import { WeaveFrameToolAction } from "@inditextech/weavejs-sdk";
----

== Instantiation

[source,typescript]
----
new WeaveFrameToolAction(config?: WeaveFrameToolCallbacks);
----

== Configuration

[source,typescript]
----
type WeaveFrameToolCallbacks = {
  onPropsChange?: WeaveActionPropsChangeCallback; // <1>
};
----
<1> `onPropsChange` (optional): A callback function that is called when the properties
of the action change. The callback receives an object as parameter with the

== Methods

=== updateProps

[source,typescript]
----
updateProps(props: WeaveElementAttributes): void;
----

Update the properties of the action. Ideal for setting properties of the freeform line,
like its color, stroke size, etc.

== Events

If the keys kbd:[Enter] or kbd:[Esc] are pressed, the action is cancelled.

On touch devices, select again the xref:api-reference:sdk/actions/selection-tool.adoc[Selection Tool]
to finish or cancel the action.

== TypeScript Types

[source,typescript]
----
type WeaveActionPropsChangeCallback = (
  props: WeaveElementAttributes
) => void;

type WeaveElementAttributes = {
  [key: string]: any;
  id?: string;
  nodeType?: string;
  children?: WeaveStateElement[];
};

type WeaveStateElement = {
  key: string;
  type: string;
  props: WeaveElementAttributes;
};

type WeaveFrameToolCallbacks = {
  onPropsChange?: WeaveActionPropsChangeCallback;
};
----
