sonar.projectKey=InditexTech_weavejs
sonar.projectName=weavejs
sonar.cpd.exclusions=\
code/packages/create-backend-app/**/*,\
code/packages/create-frontend-app/**/*,\
**/tsdown.config.ts,\
**/vitest.config.ts,\
**/vitest.setup.ts,\
**/__tests__/**,\
**/*.test.ts
sonar.javascript.lcov.reportPaths=./code/coverage/lcov.info