= Backend

In order to make the backend functional, we need to setup a _Next.js_
https://nextjs.org/docs/14/pages/building-your-application/configuring/custom-server[custom server]
to later on integrate **Weave.js** websockets store, the store will handle for Us
the shared-state management, clients networking, persistence and awareness events.

== Overview

To setup **Weave.js** backend over our _Next.js_ project (on a single artifact), we need
to fully complete this checklist:

* [ ] Install the **Weave.js** backend dependencies.
* [ ] Setup the _Next.js_ custom server.
* [ ] Integrate **Weave.js** into the custom server:
** [ ] Define the function handlers (get/set) for the shared-state persistence.
** [ ] Setup the **Weave.js** websockets store on the custom server. 

== Step 3.1. Install the Weave.js backend dependencies

First lets install the **Weave.js** websocket store dependencies, on your root project folder,
execute the following command:

[source,shell]
----
npm install ws @inditextech/weavejs-store-websockets
----

[sidebar]
--
This command will install:

- The `ws` library, which is a simple WebSocket client and server implementation. For now we will
just focus only on the server side.
- **Weave.js** `@inditextech/weavejs-store-websockets` websockets store library. It abstract all the
implementation that handles the management of the shared-stated between the clients and provides an
interface for it's persistence (persistence wise were agnostic). As developer you just need to define
some configuration and callbacks to handle the persistence of the shared-state on your end
(database, blob storage, etc.)
--

== Step 3.2. Setup the Next.js custom server

In order to have a frontend and backend on the same artifact on top of _Next.js_ we need to implement 
a https://nextjs.org/docs/14/pages/building-your-application/configuring/custom-server[custom server]
on _Next.js_, and later on include the necessary **Weave.js** backend logic.

[IMPORTANT]
====
For production environments, you should consider using a separate backend
server to handle the **Weave.js** backend logic.
====

To start , lets install the necessary dependencies for the custom server with the following commands:

[source,shell]
----
npm install cross-env express # <1>
----
<1> Dependencies needed on runtime.

[source,shell]
----
npm install -D ts-node nodemon @types/express # <1>
----
<1> Dependencies only needed on LDE or build time.


=== TypeScript configuration

Second, we need to setup the the TypeScript configuration for the server part.

. Create a `tsconfig.server.json` file on the root of your project with the following content:
+
[source,json]
----
include::ROOT:example$tsconfig.server.json[]
----
+
. Setup the transpilation of the server files from TypeScript to JavaScript. Create a
`nodemon.json` file on the root of your project with the following content:
+
[source,json]
----
include::ROOT:example$nodemon.json[]
----

[NOTE]
====
This sections uses https://www.npmjs.com/package/nodemon[nodemon] a tool that helps on the LDE
by automatically restarting the underlying Node.js application when a file changes.
====

=== Custom server logic

Define the custom server logic by creating a file named `server.ts` on the root of your project
with the following content:

[source,typescript]
----
include::ROOT:example$server.ts[]
----

[NOTE]
====
This sections uses https://expressjs.com/[express] a web framework for Node.js as the
underlying server for the custom server.
====

=== Custom server tooling

In order to properly use the custom server on: the LDE and when building the application,
we need to customize the dependant scripts on your `package.json`: the `dev`, `build` and `start` ones.
Change the scripts definitions with the following content:

[source,json]
----
{
  "scripts": {
    "dev": "nodemon", # <1>
    "build": "next build && tsc --project tsconfig.server.json", # <2>
    "start": "cross-env NODE_ENV=production node dist/server.js" # <3>
  }
}
----
<1> Script that launches the LDE server.
<2> Script that build the _Next.js_ application.
<3> Script that runs the built _Next.js_ application.

'''

Finally lets test that the _Next.js_ project keeps starting with the new custom server configuration,
on the project root folder just run the following command:

[source,shell]
----
npm run dev
----

Navigate to http://localhost:3000 on a browser, you should still see the _Next.js_ default application running
and the console should have no errors at all.

== Step 3.3. Integrate Weave.js into the backend

Now the _Next.js_ custom server is completely setup, lets proceed to add the necessary **Weave.js** 
backend logic for that we will use the xref:store-websockets:index.adoc[Websockets store] library
(`@inditextech/weavejs-store-websockets`). We just only need to:

- Define how to handle the persistence of the shared-state.
- Instantiate the xref:store-websockets:server.adoc#weave-websockets-server[WeaveWebsocketsServer] class from
the library `@inditextech/weavejs-store-websockets` and configure it.

=== Setup the shared-state persistence handlers

On this step we're going to define the persistence logic for the shared-state. For our quickstart we'll
use the file system as our persistence layer.

Create a `persistence.ts` file on the project root and set it's content to:

[source,typescript]
----
include::ROOT:example$persistence.ts[]
----
<1> Import necessary Node.js dependencies to handle the file system.
<2> `fetchRoom`: Fetches a previously saved shared-state of a room by its ID from the file system.
<3> `persistRoom`: Persist the shared-state of a room by its ID onto the file system.

=== Setup the Weave.js Websockets store

Finally lets setup the **Weave.js** store handler, in this case we'll setup the Websockets transport.

On the custom server file `server.ts`, let's add the necessary logic to use the `@inditextech/weavejs-store-websockets`
store handler. You can replace the contents of `server.ts` with this content:

[source,typescript]
----
include::ROOT:example$server.mod-1.ts[]
----
<1> Import **Weave.js** Websockets store dependency.
<2> Import persistence handlers previously defined.
<3> Define a regex to identify the **Weave.js** Websockets connection URI.
<4> Extract the underlying HTTP server.
<5> Define the configuration for the xref:store-websockets:server.adoc#weave_websockets_server[WeaveWebsocketsServer] class. 
<6> Define the property `performUpgrade`, this indicates which URIs are valid for the Websocket upgrade protocol
(upgrade from HTTP to WEBSOCKETS)
<7> Define the property `extractRoomId`, this indicates how to extract the room ID from the Websocket connection URI.
<8> Use the previous `fetchRoom` function for persistence management.
<9> Use the previous `persistRoom` function for persistence management.
<10> Instantiate the xref:store-websockets:server.adoc#weave_websockets_server[WeaveWebsocketsServer] class.
<11> Attach the **Weave.js** Websockets server to the HTTP server.

'''

Finally lets test that the project keeps starting with the changes made to the custom server, just run
the following command:

[source,shell]
----
npm run dev
----

Navigate to http://localhost:3000 on a browser, you should still see the _Next.js_ default application running
and the console should have no errors at all.

== Next steps

Let's now setup the xref:ROOT:quickstart.frontend.adoc[frontend side] of the application.
