= API reference

**Weave.js** provides and maintain the following packages, all available on the
NPM public registry:

* `@inditextech/weavejs-sdk`
* `@inditextech/weavejs-react`
* `@inditextech/weavejs-store-azure-web-pubsub`
* `@inditextech/weavejs-store-websockets`
* `@inditextech/weavejs-types`

== SDK

[source,shell]
----
npm install @inditextech/weavejs-sdk
----

This is the main **Weave.js** package. The SDK provides:

- The xref:api-reference:sdk/weave.adoc[Weave] class, which provides an API to interact with the SDK.
Here you can find all the necessary functionality for the frontend side.
- All the xref:architecture:nodes.adoc[Nodes], xref:architecture:plugins.adoc[Plugins] and
xref:architecture:actions.adoc[Actions] maintained by **Weave.js** team.

[NOTE]
====
Remember that the SDK is totally agnostic of UI frameworks.
====

== React Helper Library

[source,shell]
----
npm install @inditextech/weavejs-react
----

A helper library that helps integrate with React. Provides:

* A global state store defined using https://zustand.docs.pmnd.rs/getting-started/introduction[Zustand]
to manage the **Weave.js** instance state.
* A provider component named xref:api-reference:react/weave-provider.adoc[WeaveProvider] to setup
and instantiate the **Weave.js** instance.
* A hook named xref:api-reference:react/use-weave.adoc[useWeave] hook to access the **Weave.js**
instance.

== Store providers

Store providers are an abstraction to handle all things related to the shared-state on
the backend side. As today we provide and maintain the following store providers:

=== Azure Web PubSub

[source,shell]
----
npm install @inditextech/weavejs-store-azure-web-pubsub
----

Provides the necessary APIs:

* xref:api-reference:stores/azure-web-pubsub/client.adoc[Client API]
* xref:api-reference:stores/azure-web-pubsub/server.adoc[Server API]

To setup a **Weave.js** store that uses https://azure.microsoft.com/en-us/products/web-pubsub[_Azure Web PubSub_]
as transport.

'''

=== Websockets

[source,shell]
----
npm install @inditextech/weavejs-store-websockets
----

Provides the necessary APIs:

* xref:api-reference:stores/websockets/client.adoc[Client API]
* xref:api-reference:stores/websockets/server.adoc[Server API] 

To setup a **Weave.js** store that uses https://developer.mozilla.org/en-US/docs/Web/API/WebSockets_API[_Websockets API_]
as transport.

== TypeScript types

[source,shell]
----
npm install @inditextech/weavejs-types
----

A package with all xref:api-reference:types/index.adoc[types definitions] necessary to
support TypeScript.
