#!/usr/bin/env sh
cd code
CODE_CHANGES=$(npm run changed:files -- "code/**/*" 2> /dev/null)
if [ "${CODE_CHANGES}" != "0" ]
then
  npm run git:pre-push
fi
cd ../docs
DOCS_CHANGES=$(npm run changed:files -- "docs/**/*" 2> /dev/null)
if [ "${DOCS_CHANGES}" != "0" ]
then
  npm run changed:files -- "docs/**/*"
  npm run git:pre-push
fi