= WeaveNodesSelectionPlugin

The **WeaveNodesSelectionPlugin** plugin enables users to select one or multiple
nodes on the canvas through clicks, shift-clicks, or drag-selection (marquee). It
provides the foundation for interactions like moving, grouping, editing, or deleting
elements.

This plugin handles selection state, visual highlighting, and integrates with other
plugins (like keyboard shortcuts or transformation tools) to enable rich, interactive
workflows. It’s essential for building intuitive, user-friendly collaborative
interfaces.

== Import

[source,typescript]
----
import { WeaveNodesSelectionPlugin } from "@inditextech/weavejs-sdk";
----

== Instantiation

[source,typescript]
----
new WeaveNodesSelectionPlugin(config: WeaveNodesSelectionPluginCallbacks);
----

== Configuration

[source,typescript]
----
type WeaveNodesSelectionPluginCallbacks = {
  onNodesChange: WeaveNodesSelectionChangeCallback; // <1>
  onStageSelection?: WeaveNodesSelectionStageSelectionCallback; // <2>
}
----
<1> `onNodesChange`: A callback function that is called when the selection
of nodes changes. The callback receives an array of the selected nodes as a parameter.
<2> `onStageSelection` (optional): A callback function that is called when the
user clicks on the stage to clear the selection. The callback receives no parameters.

== Methods

None

== TypeScript Types

[source,typescript]
----
type WeaveElementAttributes = {
  [key: string]: any;
  id?: string;
  nodeType?: string;
  children?: WeaveStateElement[];
};

type WeaveStateElement = {
  key: string;
  type: string;
  props: WeaveElementAttributes;
};

type WeaveSelection = {
  instance: Konva.Shape | Konva.Group;
  node: WeaveStateElement;
}

type WeaveNodesSelectionChangeCallback = (
  nodes: WeaveSelection[]
) => void;

type WeaveNodesSelectionStageSelectionCallback = () => void;

type WeaveNodesSelectionPluginCallbacks = {
  onNodesChange: WeaveNodesSelectionChangeCallback;
  onStageSelection?: WeaveNodesSelectionStageSelectionCallback;
};
----
