= WeaveStageZoomPlugin

The **WeaveStageZoomPlugin** plugin enables smooth zooming in and out of the canvas,
allowing users to focus on details or get an overview of the entire workspace. It
supports mouse wheel, trackpad gestures, and programmatic control, with customizable
zoom levels.

This plugin enhances navigation and usability in complex visual tools like whiteboards,
diagrams, or design interfaces. It integrates seamlessly with the panning and resize plugins
to provide a fully scalable and interactive canvas experience.

== Import

[source,typescript]
----
import { WeaveStageZoomPlugin } from "@inditextech/weavejs-sdk";
----

== Instantiation

[source,typescript]
----
new WeaveStageZoomPlugin(config?: WeaveStageZoomPluginParams);
----

== Configuration

[source,typescript]
----
type WeaveStageZoomPluginParams = {
  zoomSteps?: number[]; // <1>
  defaultZoom?: number; // <2>
  onZoomChange?: WeaveStageZoomOnZoomChangeCallback; // <3>
}
----
<1> `zoomSteps` (optional): An array of zoom levels to snap to.
+
Defaults to `[0.1, 0.25, 0.5, 1, 2, 4, 8]`.
<2> `defaultZoom` (optional): The initial zoom level. Defaults to `1`.
<3> `onZoomChange` (optional): A callback function that is called when the zoom
level changes. The callback receives an object as parameter with the following properties:
+
* `scale`: The actual scale of the canvas.
* `zoomSteps`: The array of zoom levels.
* `actualStep`: The index of the current zoom level in the `zoomSteps` array.
* `onDefaultStep`: A boolean indicating if the current zoom level is one of the default steps.
* `canZoomIn`: A boolean indicating if it's possible to zoom in further.
* `canZoomOut`: A boolean indicating if it's possible to zoom out further.

== Methods

None

== TypeScript Types

[source,typescript]
----
type WeaveStageZoomChanged = {
  scale: number;
  zoomSteps: number[];
  actualStep: number;
  onDefaultStep: boolean;
  canZoomIn: boolean;
  canZoomOut: boolean;
};

type WeaveStageZoomOnZoomChangeCallback = (zoomInfo: WeaveStageZoomChanged) => void;

type WeaveStageZoomPluginParams = {
  zoomSteps?: number[]; // <1>
  defaultZoom?: number; // <2>
  onZoomChange?: WeaveStageZoomOnZoomChangeCallback; // <3>
}
----
