= WeaveRegularPolygonNode (deprecated)
:description: Ellipse node API Reference

.Deprecated
[WARNING]
====
This node is deprecated. Use the xref:sdk:api-reference/nodes/polygon.adoc[WeavePolygonNode] instead.
====

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/nodes/regular-polygon/regular-polygon.ts[WeaveRegularPolygonNode]
class represents a basic regular polygon shape within the Weave.js canvas.

Built on top of Konva’s https://konvajs.org/api/Konva.RegularPolygon.html[RegularPolygon] class shape under the hood, the WeaveRegularPolygonNode
offers a simple yet powerful primitive that supports full interaction, styling, and real-time synchronization.

The class extends the xref:sdk:api-reference/nodes/node.adoc[WeaveNode] class

== Type

This node `nodeType` property value is `regular-polygon`.

== Import

[source,shell]
----
import { WeaveRegularPolygonNode } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveRegularPolygonNode(params?: WeaveRegularPolygonNodeParams);
----

== TypeScript types

[source,ts]
----
type WeaveNodeTransformerProperties = Konva.TransformerConfig;

type WeaveRegularPolygonProperties = {
  transform: WeaveNodeTransformerProperties;
};

type WeaveRegularPolygonNodeParams = {
  config: Partial<WeaveRegularPolygonProperties>;
};
----

== Parameters

For `WeaveRegularPolygonNodeParams`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[config] | mono:[Partial<WeaveRegularPolygonProperties>] | label:green[Required] | Config parameters for the node.
|===

For `WeaveRegularPolygonProperties`:

[cols="5*"]
|===
| Property | Type | Required | Default | Description

| mono:[transform] | mono:[object] |  | mono:[check default values] | Setup the transform properties for the regular polygon (if can be resized, rotated, anchors, etc.).
|===

== Default values

[source,ts]
----
const WEAVE_TRANSFORMER_ANCHORS = {
  ["TOP_LEFT"]: "top-left",
  ["TOP_CENTER"]: "top-center",
  ["TOP_RIGHT"]: "top-right",
  ["MIDDLE_RIGHT"]: "middle-right",
  ["MIDDLE_LEFT"]: "middle-left",
  ["BOTTOM_LEFT"]: "bottom-left",
  ["BOTTOM_CENTER"]: "bottom-center",
  ["BOTTOM_RIGHT"]: "bottom-right",
};

const WEAVE_DEFAULT_ENABLED_ANCHORS: string[] = Object.values(
  WEAVE_TRANSFORMER_ANCHORS
);

const WEAVE_DEFAULT_TRANSFORM_PROPERTIES: WeaveNodeTransformerProperties = {
  rotateEnabled: true,
  resizeEnabled: true,
  enabledAnchors: WEAVE_DEFAULT_ENABLED_ANCHORS,
  borderStrokeWidth: 3,
  padding: 0,
};
----
