= WeaveStrokeNode
:description: Stroke node API Reference

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/nodes/stroke/stroke.ts[WeaveStrokeNode]
class represents a multi-point continuous line or path on the Weave.js canvas. It is a versatile and essential node type for
building tools like freehand drawing.

Built on top of Konva’s https://konvajs.org/api/Konva.Shape.html[Shape] class shape under the hood, the WeaveStrokeNode
offers full control over the line’s geometry, style, and behavior—all synchronized in real time across users.

The class extends the xref:sdk:api-reference/nodes/node.adoc[WeaveNode] class

== Type

This node `nodeType` property value is `stroke`.

== Import

[source,shell]
----
import { WeaveStrokeNode } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveStrokeNode(params?: WeaveStrokeNodeParams);
----

== TypeScript types

[source,ts]
----
type WeaveNodeTransformerProperties = Konva.TransformerConfig;

type WeaveStrokeProperties = {
  splineResolution: number; // Spline resolution
  resamplingSpacing: number; // Spacing for resampling points
  transform?: WeaveNodeTransformerProperties;
};

type WeaveStrokeNodeParams = {
  config: Partial<WeaveStrokeProperties>;
};

type WeaveStrokePoint = {
  x: number;
  y: number;
  pressure: number;
};
----

== Parameters

For `WeaveStrokeNodeParams`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[config] | mono:[Partial<WeaveStrokeNodeParams>] | label:green[Required] | Config parameters for the node.
|===

For `WeaveStrokeNodeParams`:

[cols="5*"]
|===
| Property | Type | Required | Default | Description

| mono:[splineResolution] | mono:[number] |  | mono:[8] | Resolution of the interpolated spline to smooth the curve
|===

== Default values

[source,ts]
----
const WEAVE_STROKE_NODE_DEFAULT_CONFIG = {
  splineResolution: 8,
  resamplingSpacing: 2,
};
----
