= WeaveCommentsRendererPlugin
:description: Render comment nodes on a special layer to manage and interact with them

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/plugins/comments-renderer/comments-renderer.ts[WeaveCommentsRendererPlugin]
class represents a plugin that renders a set of comments (headless based on the defined Entity model)
on a special layer on the stage.

The class extends the xref:sdk:api-reference/plugins/plugin.adoc[WeavePlugin] class

== Name

This plugin `name` property value is `commentsRenderer`.

== Import

[source,shell]
----
import { WeaveCommentsRendererPlugin } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveCommentsRendererPlugin<T>(params: WeaveConnectedUsersPluginParams<T>);
----

== TypeScript types

[source,ts]
----
type WeaveCommentsRendererModel<T> = {
  getId: (comment: T) => string;
  getUser: (comment: T) => WeaveUser;
  getPosition: (comment: T) => Vector2d;
  getStatus: (comment: T) => WeaveCommentStatus;
};

type WeaveCommentsRendererPluginConfig<T> = {
  model: WeaveCommentsRendererModel<T>;
  getUser: () => WeaveUser;
  getUserBackgroundColor: (
    user: WeaveUser
  ) => string | CanvasGradient | undefined;
  getUserForegroundColor: (
    user: WeaveUser
  ) => string | CanvasGradient | undefined;
};

type WeaveCommentsRendererPluginParams<T> = {
  config: WeaveCommentsRendererPluginConfig<T>;
};
----

== Parameters

For `WeaveConnectedUsersPluginParams<T>`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[config] | mono:[WeaveCommentsRendererPluginConfig<T>] | label:green[Required] | Config parameters for the plugin.
|===

For `WeaveCommentsRendererPluginConfig<T>`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[model] | mono:[WeaveCommentsRendererModel<T>] | label:green[Required] | Setup the Entity model 
| mono:[getUser] | mono:[() => WeaveUser] | label:green[Required] | A function that return the actual user model
| mono:[getUserBackgroundColor] | mono:[(user: WeaveUser) => string \| CanvasGradient \| undefined] | label:green[Required] | A function that is called to define a user background color base on its model.
| mono:[getUserForegroundColor] | mono:[(user: WeaveUser) => string \| CanvasGradient \| undefined] | label:green[Required] | A function that is called to define a user foreground color base on its model.
|===
