= WeaveContextMenuPlugin
:description: Trigger a contextual menu on the canvas

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/plugins/context-menu/context-menu.ts[WeaveContextMenuPlugin]
class that enables custom right-click (context) menus on the canvas. It provides a flexible and modular way
to trigger context-aware actions based on where and what the user right-clicks—whether it's a node, empty
space, or selection.

This plugin enhances usability by letting developers define dynamic, context-sensitive options, making the
user experience faster, more intuitive, and better organized.

The class extends the xref:sdk:api-reference/plugins/plugin.adoc[WeavePlugin] class

== Name

This plugin `name` property value is `contextMenu`.

== Import

[source,shell]
----
import { WeaveContextMenuPlugin } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveContextMenuPlugin(params?: WeaveStageContextMenuPluginParams);
----

== TypeScript types

[source,ts]
----
type WeaveStageContextMenuPluginParams = {
  config?: WeaveStageContextMenuPluginConfig;
};

type WeaveStageContextMenuPluginConfig = {
  xOffset?: number;
  yOffset?: number;
};

type WeaveStageContextMenuPluginOnNodeContextMenuEvent = {
  selection: WeaveSelection[];
  point: Vector2d;
  visible: boolean;
};
----

== Parameters

For `WeaveStageContextMenuPluginParams`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[config] | mono:[WeaveStageContextMenuPluginConfig] | label:green[Required] | Config parameters for the plugin.
|===

For `WeaveStageContextMenuPluginConfig`:

[cols="5*"]
|===
| Property | Type | Required | Default | Description

| mono:[xOffset] | mono:[number] |  | mono:[4] | X-axis offset of the click point in pixels.
| mono:[yOffset] | mono:[number] |  | mono:[4] | Y-axis offset of the click point in pixes
|===

== Events

=== onNodeContextMenu

[source,ts]
----
onNodeContextMenu: WeaveStageContextMenuPluginOnNodeContextMenuEvent;
----

The `onNodeContextMenu` event is called when an user triggers the context menu on a node or the stage.
