= WeaveNodesMultiSelectionFeedbackPlugin
:description: Activate support to provide more feedback when multi-selecting nodes on the canvas

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/plugins/nodes-multi-selection-feedback/nodes-multi-selection-feedback.ts[WeaveNodesMultiSelectionFeedbackPlugin]
class that provides feedback to the end-users when multi-selecting nodes on the canvas.

Selection is a critical foundation for enabling further interactions like moving, grouping, deleting,
copying, or applying bulk actions on nodes.

The class extends the xref:sdk:api-reference/plugins/plugin.adoc[WeavePlugin] class

== Name

This plugin `name` property value is `nodesMultiSelectionFeedback`.

== Import

[source,shell]
----
import { WeaveNodesMultiSelectionFeedbackPlugin } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveNodesMultiSelectionFeedbackPlugin(params?: WeaveNodesMultiSelectionFeedbackPluginParams);
----

== TypeScript types

[source,ts]
----
type WeaveNodesMultiSelectionFeedbackStyle = {
  stroke: string;
  strokeWidth: number;
  fill: string;
};

type WeaveNodesMultiSelectionFeedbackConfig = {
  style: WeaveNodesMultiSelectionFeedbackStyle;
};

type WeaveNodesMultiSelectionFeedbackPluginConfig =
  DeepPartial<WeaveNodesMultiSelectionFeedbackConfig>;

type WeaveNodesMultiSelectionFeedbackPluginParams = {
  config?: WeaveNodesMultiSelectionFeedbackPluginConfig;
};
----

== Parameters

For `WeaveNodesMultiSelectionFeedbackPluginParams`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[config] | mono:[WeaveNodesMultiSelectionFeedbackPluginConfig] |  | Config parameters for the plugin.
|===

For `WeaveNodesMultiSelectionFeedbackPluginConfig`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[style] | mono:[WeaveNodesMultiSelectionFeedbackStyle] |  | Selector config (Konva Transformer configuration).
|===

For `WeaveNodesMultiSelectionFeedbackStyle`:

[cols="5*"]
|===
| Property | Type | Required | Default | Description

| mono:[stroke] | mono:[string] |  | mono:[#ff2c2cff] | The color of the stroke (edge)
| mono:[strokeWidth] | mono:[number] |  | mono:[2] | The width of the stroke (edge)
| mono:[fill] | mono:[string] |  | mono:[transparent] | The fill of the selector
|===
