= WeaveUsersPresencePlugin
:description: Showcase what users are doing in real-time on the canvas

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/plugins/users-presence/users-presence.ts[WeaveUsersPresencePlugin]
class that enables real-time sharing of operations data (drag, transform, etc.) across all
connected users on the collaborative canvas. It will then display this changes as awareness
without merging them on the room state.

This plugin helps create a shared sense of presence, making collaborative tools feel dynamic,
interactive, and truly multi-user.

The class extends the xref:sdk:api-reference/plugins/plugin.adoc[WeavePlugin] class

== Name

This plugin `name` property value is `usersPresence`.

== Import

[source,shell]
----
import { WeaveUsersPresencePlugin } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveUsersPresencePlugin(params: WeaveUsersPresencePluginParams);
----

== TypeScript types

[source,ts]
----
type WeaveUser = {
  [key: string]: any;
  name: string;
  email: string;
};

type WeaveUsersPresencePluginConfig = {
  awarenessThrottleMs: number;
  getUser: () => WeaveUser;
};

type WeaveUsersPresencePluginParams = {
  config: Pick<WeaveUsersPresencePluginConfig, "getUser"> &
    Partial<Omit<WeaveUsersPresencePluginConfig, "getUser">>;
};

type WeaveUserPresenceInformation = Record<string, WeaveUserPresence<unknown>>;

type WeaveUserPresence<T> = {
  userId: string;
  nodeId: string;
  attrs: T;
};

type WeaveUserPresenceKey = typeof WEAVE_USER_PRESENCE_KEY;
----

== Parameters

For `WeaveUsersPresencePluginParams`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[config] | mono:[WeaveUsersPresencePluginConfig] |  | Config parameters for the plugin.
|===

For `WeaveUsersPresencePluginConfig`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[getUser] | mono:[() => WeaveUser] |  | A function that returns the actual instance user metadata.
|===
