= Room page

On this guide we build the **Room** page. This page will render the collaborative
canvas once an user joins the room.

== Overview

To setup the **Room** page on the _Next.js_ project, we need to fully complete
this checklist:

* [ ] Define the page component.
* [ ] Install the UI building block components.
* [ ] Define a constants file.
* [ ] Define the page React hooks.
* [ ] Define the base styles.
* [ ] Define the page React components.

== Step 4.4.1. Define the page component

To setup the `Room` page component, follow this steps:

. Create a folder named `room` on the `app` folder.
. Create a folder named `[roomId]` on the `app/room` folder.
. Create a file named `page.tsx` on the `app/room/[roomId]` folder with the following content:
+
[source,typescript]
----
include::quickstart:example$app/room/roomId/page.tsx[]
----

== Step 4.2.2. Install the UI building block components

Lets now setup the necessary https://ui.shadcn.com/docs[Shadcn/UI] components for the `Room` page.

We'll be using the link:https://ui.shadcn.com/docs/cli[Shadcn/UI CLI] to install the UI components. Accept
all the defaults from the CLI options.

. First lets install the https://ui.shadcn.com/docs/components/tooltip[Tooltip] component
+
[source,typescript]
----
npx shadcn@latest add tooltip
----
+
. Install the https://ui.shadcn.com/docs/components/dropdown-menu[Dropdown Menu] component
+
[source,typescript]
----
npx shadcn@latest add dropdown-menu
----
+
. Finally install the https://ui.shadcn.com/docs/components/avatar[Avatar] component
+
[source,typescript]
----
npx shadcn@latest add avatar
----

== Step 4.4.3. Define a constants file

Lets define a set of constants that will define the **Weave.js** Nodes, Plugins and Actions
that we will use, follow this steps:

. Lets create a folder named `utils` on the `components` folder.
. Create a file named `constants.ts` on the `components/utils` folder with the following content:
+
[source,typescript]
----
include::quickstart:example$components/utils/constants.ts[]
----
<1> Import the **Weave.js** SDK dependency.
<2> Setup the Fonts available on **Weave.js**.
<3> Define the nodes we'll use on this example.
<4> Define the actions we'll use on this example.
<5> Define the custom plugins we'll use on this example. By default the xref:api-reference:react/weave-provider.adoc[WeaveProvider]
provider pre-defines a set of plugins. On this case we can override them or add extra plugins.

== Step 4.4.4. Define the page React hooks

Lets define the hooks with the logic for the `Room` page, this way we separate the component logic
from the UI logic. To start create a `hooks` folder on the `components` folder.

=== useHandleRouteParams

On the `components/hooks` folder, create a file named `use-handle-route-params.ts` with
the following content:

[source,typescript]
----
include::quickstart:example$hooks/use-handle-route-params.ts[]
----

=== useGetWebsocketsStore

On the `components/hooks` folder, create a file named `use-get-websockets-store.ts` with the following
content:

[source,typescript]
----
include::quickstart:example$hooks/use-get-websockets-store.ts[]
----

=== useGetWeaveJsProps

On the `components/hooks` folder, create a file named `use-get-weave-js-props.ts` with the following
content:

[source,typescript]
----
include::quickstart:example$hooks/use-get-weave-js-props.ts[]
----

=== useContextMenu

On the `components/hooks` folder, create a file named `use-context-menu.ts` with the following
content:

[source,typescript]
----
include::quickstart:example$hooks/use-context-menu.ts[]
----

== Step 4.4.5. Define the page React components

Lets first setup a folder to put all our components:

. Create a `room` folder on the `components` folder.
. Create a `overlays` folder on the `components` folder.
. Create a `context-menu` folder on the `components` folder.

=== Room

To setup the `Room` React component, create a file named `room.tsx` on the `components/room`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/room/room.tsx[]
----

=== RoomLayout

To setup the `RoomLayout` React component, create a file named `room.layout.tsx` on the `components/room`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/room/room.layout.tsx[]
----

=== RoomLoader

To setup the `Room` React component, create a file named `room-loader.tsx` on the `components/room`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/room/room-loader.tsx[]
----

=== ConnectedUsers

To setup the `ConnectedUsers` React component, create a file named `connected-users.tsx` on the `components/overlays`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/overlays/connected-users.tsx[]
----

=== ConnectionStatus

To setup the `ConnectionStatus` React component, create a file named `connection-status.tsx` on the `components/overlays`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/overlays/connection-status.tsx[]
----

=== RoomInformationOverlay

To setup the `RoomInformationOverlay` React component, create a file named `room-information-overlay.tsx` on the `components/overlays`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/overlays/room-information-overlay.tsx[]
----

=== RoomUsersOverlay

To setup the `RoomUsersOverlay` React component, create a file named `room-users-overlay.tsx` on the `components/overlays`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/overlays/room-users-overlay.tsx[]
----

=== ToolbarButton

To setup the `ToolbarButton` React component, create a file named `toolbar-button.tsx` on the `components/overlays`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/overlays/toolbar-button.tsx[]
----

=== Toolbar

To setup the `Toolbar` React component, create a file named `toolbar.tsx` on the `components/overlays`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/overlays/toolbar.tsx[]
----

=== ToolsOverlay

To setup the `ToolsOverlay` React component, create a file named `tools-overlay.tsx` on the `components/overlays`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/overlays/tools-overlay.tsx[]
----

=== ZoomHandlerOverlay

To setup the `ZoomHandlerOverlay` React component, create a file named `zoom-handler-overlay.tsx` on the `components/overlays`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/overlays/zoom-handler-overlay.tsx[]
----

=== ContextMenu

To setup the `ContextMenu` React component, create a file named `context-menu` on the `components/context-menu`
folder with the following content:

[source,typescript]
----
include::quickstart:example$components/context-menu/context-menu.tsx[]
----

Then uncomment all the commented lines on the `store/store.ts` file.

== Next steps

Let's now xref:quickstart:index.adoc#_step_5_run_the_project[run the project] to test the full integration.
