= Quickstart

Lets integrate ** Weave.js** on top of a https://nextjs.org/docs[_Next.js_] application.

[NOTE]
====
The usage of _Next.js_ on the quickstart allow us to have the frontend and backend
on the same artifact, thus simplifies the quickstart process. Also is one of the most understand
frameworks built on top of React.

For a detailed code on how to setup **Weave.js** on separated artifacts, check our
showcase artifacts implementations repositories:

- https://github.com/InditexTech/weavejs-backend[Backend]
- https://github.com/InditexTech/weavejs-frontend[Frontend]
====

[IMPORTANT]
====
Take into consideration that we will use _Next.js_ version 14, as today **Weave.js**
is not compatible with React 19, which is the version of React that ships with the
latest version (v15 when writing this document) of _Next.js_.
====

== Overview

In order to have a **Weave.js** project running, we need to fully complete this
checklist:

* [ ] Install Next.js
* [ ] Install the Weave.js SDK
* [ ] Setup the backend
* [ ] Setup the frontend
* [ ] Run the project

Are you ready? Lets get started!.

== Step 1. Install Next.js

Lets start our journey by creating a new Next.js application, just run the
following command:

[source,shell]
----
npx create-next-app@next-14
----

When prompted, accept all the default values.

[NOTE]
====
The command will create a folder with your project name will proceed to install
the required dependencies.
====

When finished, navigate to the project folder and start the development server
by running the following command:

[source,shell]
----
npm run dev
----

You should be able now to open your _Next.js_ base app on a browser by navigating
to http://localhost:3000.

[NOTE]
====
You will notice that some images will fail to load, this is because _Next.js_
images URLs changed and are not available. To fix this is up to Next.js maintainers
and not us, we'll ignore it for now as it doesn't affect Us.
====

== Step 2. Install Weave.js SDK

Located on your root project folder, install the **Weave.js** SDK by
executing the following command:

[source,shell]
----
npm install @inditextech/weavejs-sdk @inditextech/weavejs-types
----

[sidebar]
--
This command will install:

- **Weave.js** `@inditextech/weavejs-sdk` main SDK library, this library provides the
xref:api-reference:sdk/weave.adoc[Weave] class, that instantiated provides an API to handle all **Weave.js**
related tasks.
- **Weave.js** `@inditextech/weavejs-types` xref:api-reference:types/index.adoc[types definitions] for TypeScript, as we're using it.
--

== Step 3. Setup the backend side

Now that the main dependencies are installed, lets first work with the backend side.

In this step we'll xref:quickstart:backend.adoc[setup the backend side] of the application.

== Step 4. Setup the frontend side

After the backend side is setup, the application also needs a frontend side where
users will visually collaborate.

In this step we'll xref:quickstart:frontend.adoc[setup the frontend side] of the application.

== Step 5. Run the project

If your completed all the previous steps, you should have a working project, so lets
run the project with the following command:

[source,shell]
----
npm run dev
----

On a browser navigate to http://localhost:3000, remember, this is the `Enter Room`
page. On it, just type a _room name_ and your _username_, then click on the `Enter`
button to join the room.

The application should navigate to http://localhost:3000/room/<roomName>, where
`<roomName>` is the name of the room you entered. On the `Room` page, you first should
notice a loader, once loaded you should be able to:

- See the collaborative canvas.
- Handle the canvas zoom and pan.
- Create a simple node like a xref:api-reference:sdk/nodes/rectangle.adoc[Rectangle] on it.

Try to open another tab with other _username_ on the same _room name_, you should be
able to see the changes made by the other user.

Congratulations! You have a working **Weave.js** application.

== Next steps

Now that you've completed the quickstart, you're ready to dive deeper into **Weave.js** and unlock its
full potential. Here are some of our recommended next steps:

=== Explore the Architecture

To better understand **Weave.js** xref:architecture:index.adoc[architecture] and to learn
how to build modular and interactive tools, learn how **Weave.js** is structured under
the hood and get familiar with core concepts like:

- xref:architecture:nodes.adoc[Nodes],
- xref:architecture:plugins.adoc[Plugins],
- and xref:architecture:actions.adoc[Actions].

=== Learn with the Tutorials

Check out a growing collection of xref:tutorials:index.adoc[hands-on tutorials] covering
real-world use cases: from custom nodes, actions or plugins, to the integrating collaborative features
provided by **Weave.js**.

=== Review the API Reference

Dive into the xref:api-reference:index.adoc[API reference] to explore all available methods, utilities,
and configuration options. This is your go-to resource as you start building more advanced features.

