= WeaveEllipseToolAction
:description: Add an ellipse to the canvas

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/actions/ellipse-tool/ellipse-tool.ts[WeaveEllipseToolAction]
class that allows users to create ellipse shapes on the canvas by clicking
and dragging. It provides a smooth, intuitive way to add structured, resizable
rectangular elements that can serve as building blocks for diagrams, layouts,
mockups, and more.

Each interaction results in the creation of a xref:sdk:api-reference/nodes/ellipse.adoc[WeaveEllipseNode],
added to the shared state and synchronized across all users.

While dragging, hold `Shift` to draw a circle, `Alt`/`Option` to draw from the initial point as the center, or both to combine the behaviors.

The class extends the xref:sdk:api-reference/actions/action.adoc[WeaveAction] class.

== Name

This action `name` property value is `ellipseTool`.

== Import

[source,shell]
----
import { WeaveEllipseToolAction } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveEllipseToolAction();
----
