= WeaveExportNodesToolAction
:description: Export the selected nodes as an image

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/actions/export-nodes-tool/export-nodes-tool.ts[WeaveExportNodesToolAction]
class that allows users to export a specific selection of nodes from the canvas as a standalone image file (e.g., PNG or JPEG).
This action is especially useful when users want to extract visual components from the canvas for sharing, documentation, thumbnails,
or reuse outside the app.

It works by rendering the selected node(s) to an off-screen canvas, preserving their current visual appearance, and triggering a downloadable
export.

The class extends the xref:sdk:api-reference/actions/action.adoc[WeaveAction] class.

== Name

This action `name` property value is `exportNodesTool`.

== Import

[source,shell]
----
import { WeaveExportNodesToolAction } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveExportNodesToolAction();
----

== TypeScript types

[source,ts]
----
const WEAVE_EXPORT_FORMATS: {
  readonly PNG: "image/png";
  readonly JPEG: "image/jpeg";
};

type WeaveExportNodeOptions = {
  format?: typeof WEAVE_EXPORT_FORMATS.PNG;
  padding?: number;
  pixelRatio?: number;
  backgroundColor?: string;
  quality?: number;
};

type WeaveExportNodesActionParams = {
  nodes: WeaveElementInstance[];
  boundingNodes?: (nodes: Konva.Node[]) => Konva.Node[];
  options?: WeaveExportNodesOptions;
  download?: boolean;
};
----

== Trigger function params

[source,ts]
----
trigger(cancelAction: () => void, params?: WeaveExportNodesActionParams): Promise<void>;
----

For `WeaveExportNodesActionParams`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[node] | mono:[WeaveElementInstance] | label:green[Required] | The node instance to export as image.
| mono:[boundingNodes] | mono:[(nodes: Konva.Node[\]) => Konva.Node[\]] |  | A function that defines the bounding node
| mono:[options] | mono:[WeaveExportNodeOptions] |  | The exported image options.
| mono:[download] | mono:[boolean] |  | If true, triggers a download, if false, return the image as dataURL
|===

For `WeaveExportNodeOptions`:

[cols="5*"]
|===
| Property | Type | Required | Default | Description

| mono:[format] | mono:[WeaveExportFormat] | label:green[Required] | mono:[WEAVE_EXPORT_FORMATS.PNG] | The format of the image to export.
| mono:[padding] | mono:[number] |  | mono:[0] | The padding to add to the image to export. In pixels.
| mono:[pixelRatio] | mono:[number] |  | mono:[1] | The pixel ratio to use on the image to export. For example 2 on a image of 400x400 generates a image of 800x800 pixels.
| mono:[backgroundColor] | mono:[string] |  | mono:[#FFFFFF] | The background color to use on the image to export. Is a CCS color value.
| mono:[quality] | mono:[number] |  | mono:[1] | The quality of the image to export. From 0 to 1.
|===
