= WeaveFitToScreenToolAction
:description: Set the zoom level so all the nodes on the stage are entirely visible on the screen

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/actions/fit-to-screen-tool/fit-to-screen-tool.ts[WeaveFitToScreenToolAction]
class that automatically adjusts the canvas viewport so that all visible content (nodes) is centered
and scaled to fit within the current view. It provides users with a convenient way to reorient the canvas,
especially after zooming or panning extensively.

This action is commonly used as a “reset view” or “zoom to fit” feature in collaborative or design tools.

The class extends the xref:sdk:api-reference/actions/action.adoc[WeaveAction] class.

== Name

This action `name` property value is `fitToScreenTool`.

== Import

[source,shell]
----
import { WeaveFitToScreenToolAction } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveFitToScreenToolAction();
----

== TypeScript types

[source,ts]
----
type WeaveFitToScreenToolActionParams = {
  previousAction: string;
};
----

== Trigger function params

[source,ts]
----
trigger(cancelAction: () => void, params?: WeaveFitToScreenToolActionParams): void;
----

For `WeaveFitToScreenToolActionParams`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[previousAction] | mono:[string] | label:green[Required] | The action to trigger after the fit-to-screen action is completed.
|===
