= WeaveFitToSelectionToolAction
:description: Set the zoom level so all the selected nodes are entirely visible on the screen

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/actions/fit-to-selection-tool/fit-to-selection-tool.ts[WeaveFitToSelectionToolAction]
class that automatically zooms and pans the canvas to fit the currently selected nodes within
the visible viewport. It helps users focus on specific elements of their work quickly, especially
in large or complex canvases.

This action is the “fit to selection” counterpart of the broader WeaveFitToScreenToolAction, offering
precise control and workflow efficiency.

The class extends the xref:sdk:api-reference/actions/action.adoc[WeaveAction] class.

== Name

This action `name` property value is `fitToSelectionTool`.

== Import

[source,shell]
----
import { WeaveFitToSelectionToolAction } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveFitToSelectionToolAction();
----

== TypeScript types

[source,ts]
----
type WeaveFitToScreenToolActionParams = {
  previousAction: string;
  smartZoom?: boolean;
};
----

== Trigger function params

[source,ts]
----
trigger(cancelAction: () => void, params?: WeaveFitToSelectionToolActionParams): void;
----

For `WeaveFitToSelectionToolActionParams`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[previousAction] | mono:[string] | label:green[Required] | The action to trigger after the fit-to-selection action is completed.
| mono:[smartZoom] | mono:[boolean] |  | If true, when fit-zooming we will only tri to zoom if nodes bounding box is overflowing stage bounding box, if not, we just center the stage on the nodes selected.
|===
