= WeaveLineToolAction (deprecated)
:description: Add a simple line to the canvas

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/actions/line-tool/line-tool.ts[WeaveLineToolAction]
class that allows users to draw a precise, vector-based line by click-and-drag to define the line.

The line becomes a xref:sdk:api-reference/nodes/line.adoc[WeaveLineNode],
synced in real time across all collaborators.

The class extends the xref:sdk:api-reference/actions/action.adoc[WeaveAction] class.

== Name

This action `name` property value is `lineTool`.

== Import

[source,shell]
----
import { WeaveLineToolAction } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveLineToolAction(params?: WeaveLineToolActionParams);
----

== TypeScript types

[source,ts]
----
type WeaveLineToolActionProperties = {
  snapAngles: {
    angles: number[]; // Angles for snapping in degrees
    activateThreshold: number;
    releaseThreshold: number;
  };
};

type WeaveLineToolActionParams = {
  config: Partial<WeaveLineToolActionProperties>;
};
----

== Parameters

For `WeaveLineToolActionParams`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[config] | mono:[Partial<WeaveLineToolActionProperties>] | label:green[Required] | Config parameters for the tool.
|===

For `WeaveLineToolActionProperties`:

[cols="5*"]
|===
| Property | Type | Required | Default | Description

| mono:[snapAngles.angles] | mono:[number] |  | mono:[10] | Array of angles (in degrees) to snap the line to when shift is pressed.
| mono:[snapAngles.activateThreshold] | mono:[number] |  | mono:[5] | Activation threshold for the angle snapping utility.
| mono:[snapAngles.releaseThreshold] | mono:[number] |  | mono:[10] | Release threshold for the angle snapping utility.
|===

== Default values

[source,ts]
----
const LINE_TOOL_DEFAULT_CONFIG = {
  snapAngles: {
    angles: [0, 45, 90, 135, 180, 225, 270, 315],
    activateThreshold: 5,
    releaseThreshold: 10,
  },
};
----
