= WeaveZoomOutToolAction
:description: Tool to export the stage as an image

== Overview

The https://github.com/InditexTech/weavejs/blob/main/code/packages/sdk/src/actions/zoom-out-tool/zoom-out-tool.ts[WeaveZoomOutToolAction]
class that allows users to incrementally zoom out from the canvas Stage.
It enables users to widen their view, making it easier to see more of the canvas
at once and navigate large collaborative spaces efficiently.

This action works in coordination with the xref:sdk:api-reference/plugins/stage-zoom.adoc[WeaveStageZoomPlugin]
plugin and ensures a smooth zooming experience without disrupting the
layout or collaboration session.

The class extends the xref:sdk:api-reference/actions/action.adoc[WeaveAction] class.

== Name

This action `name` property value is `zoomOutTool`.

== Import

[source,shell]
----
import { WeaveZoomOutToolAction } from "@inditextech/weave-sdk";
----

== Instantiation

[source,ts]
----
new WeaveZoomOutToolAction();
----

== TypeScript types

[source,ts]
----
type WeaveZoomOutToolActionParams = {
  previousAction: string;
};
----

== Trigger function params

[source,ts]
----
trigger(cancelAction: () => void, params?: WeaveZoomOutToolActionParams): void;
----

For `WeaveZoomOutToolActionParams`:

[cols="4*"]
|===
| Property | Type | Required | Description

| mono:[previousAction] | mono:[string] | label:green[Required] | The action to trigger after the zoom-out action is completed.
|===
